[GOOGLE_APPLICATION_CREDENTIALS]
type = "service_account"
project_id = "stronabiurokadom"
private_key_id = "30ae755727866ab9b544f2ea6e14ac7c0cf9194c"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQD+agiuugcCcPn4
cnY08Dpc50nbwz1fubSDITTqVPruLyVg7KXMRKWZs4ViL+I1RC1pFJBiU52yg0Se
fpGl1LwxLZne/fwmZY0Y5Dg9VVieLfwoYDJn0nXVxBqOvug6krqEOTmz7pplGGu3
7DqVHmLqWVvjNHx5onqCqLTxuqTkR9vFs3Lr580jJlzGnHF6N76E9m+Y/sT7Dosn
sNHEGFCrYC/4ElsKlUHtsDirNvC6QaqCAyaBPyA52v6v+rwWuJSFIz/+Pn7SCy1A
QY4vVkaaKYCnZkeNCeIaDihUqrSWIVkURlhulMdBXgUqTorLHr8SydtTHkMiRxgF
JV6rYjoXAgMBAAECggEAEFvVDxcbGEcXa6hAfYrs1chxcVYOfjc8qinacy7fq60Q
ZDkTOB054LYwX23gx7gIi3ctCYWC4FWcdeyBhP4205qxCCugqP9ioTUbgKYaOqGO
UzJMS2y28vXXF1KjMBD7OUFMuosfFl0JoBvqcGgxyAvS4rsfPdr6sagTam+r5pmv
cBn+98hSAXciM7ePeJuEkEaq1CINl8mbIsvPz++FwtSNnPlwNuiUUZv+RONhkqM8
+9VXD3sJaSbOdookQvVQK8tIB2pljFef6nk6VS8mQW5smP3qdbzCIh6NJB6FDJA9
FWQTcviMqVefQ1KWPN2yeqE1Ocs1Ofcwv4yN+qB4EQKBgQD/sMzwOav/Ng6BlxrL
x4d/4+cJ7aihFgfKA0ZII6PLX0g28IxexpSSqmOul1g02F11y/AbeNFZVc1kWN0F
FcY+f7HQ5EHToOLnzfUCosETOfKdRIVGjR/HRPnT0yfM4ZDFkaO/2RM2wu7t3w+x
Y0yg1Z6rt0hyI5iHe6k1dQxCbQKBgQD+uNaHcruDdbYRr/I0kk83eSIpmYtAlAji
ptluD8oTMAITbG0BeBPts8nvO75D9gLYytTH6kp84tMvVrb/txnBPQBzMK58XqYC
AhXSPKrclvgxTZXUL/RRk05zsMucy7FnEFrcMh6QgB4iqFLNSe+PlA9fDeWrvqBO
RlaGVK78EwKBgQDhZE3TuVL33wP8kmHpnpLAVvr0Eo7iqRPmrOpIbzpU7UIwQ+3J
Ig4YF6FVZ043Dz+btlGLNf59XJh4y6jRcbdWoqPxuzSXxCwhILnJQAUo2J0Yqy08
2uxXcWM0qd9cyL4gmtiZJla8oCuUflxMB3emE4kSX7e5/czYKVcoq2xKJQKBgQCk
MnZn3beuaESzZh3VcbMK6VTyR/4R5NtNb4ydfCQg9kOATdZ+qe7+vXSgeHyPxpfT
M/yx2f+mPXkw/M7+TAOYI0CVAH6ZwVF13e4/Fch2ZgMblQ3OOBNgOnrJ7N9z9YIo
E8zeQJifQVcrtCGcH9sDTMgT2BuC+GDR1FmWQiSCbQKBgQCfv3yOF205Cc5Vw6TJ
83XgE+vodV9Rqg6ieQPreUAqjz69brXg9RhjSl88ec7S7law8+Cvmi/D/LzWAv0Z
s0BHMp/wVN3cVMl3VT5UV6H+AseoFGaFRdWKc27HIZZzywRM/mfrVCKDX2GZrMPB
El0yXkZAv+XcZFvcCX121GbCTg==
-----END PRIVATE KEY-----
"""
client_email = "kontoserwisowestronakadom@stronabiurokadom.iam.gserviceaccount.com"
client_id = "113601773513281361455"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/kontoserwisowestronakadom%40stronabiurokadom.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
